version: '3'
services:
  app:
      build: ./docker/app/
      container_name: searchservice_app
      volumes:
          - ./:/usr/share/nginx/www
      working_dir: /usr/share/nginx/www
      networks:
        bridge:
          aliases:
          - searchservice_app
  nginx:
      build: ./docker/nginx
      container_name: searchservice
      links:
          - app
      volumes_from:
          - app
      ports:
          - 82:80
      networks:
        bridge:
          aliases:
          - searchservice
  elasticsearch:
      container_name: elasticsearch
      image: elasticsearch:7.17.5
      networks:
        bridge:
          aliases:
          - elastic
      ports:
          - 9200:9200
          - 9300:9300
      environment:
      - discovery.type=single-node
      - XPACK_SECURITY_ENABLED=false
      - XPACK_REPORTING_ENABLED=false
      - XPACK_MONITORING_ENABLED=false
networks:
  bridge:
    external:
      name: app_bridge
